# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: hrkfdn.ncspot
PackageVersion: 0.13.4
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ./ncspot.exe
        PortableCommandAlias: ncspot
    InstallerUrl: https://github.com/hrkfdn/ncspot/releases/download/v0.13.4/ncspot-v0.13.4-windows-x86_64.zip
    InstallerSha256: 0bc288a27413012d9ee16fd382fdccf9e209916038b148f520ea55f7ecb663dd
ManifestType: installer
ManifestVersion: 1.5.0
